# Make sure that the outputs of `store_subhalo_times.py` are correct

In [8]:
%matplotlib inline
from glob import glob
import h5py
from matplotlib import pyplot as plt
import numpy as np
import os
import pandas as pd

In [1]:
from scipy.stats import binned_statistic

help(binned_statistic)

Help on function binned_statistic in module scipy.stats._binned_statistic:

binned_statistic(x, values, statistic='mean', bins=10, range=None)
    Compute a binned statistic for one or more sets of data.
    
    This is a generalization of a histogram function.  A histogram divides
    the space into bins, and returns the count of the number of points in
    each bin.  This function allows the computation of the sum, mean, median,
    or other statistic of the values (or set of values) within each bin.
    
    Parameters
    ----------
    x : (N,) array_like
        A sequence of values to be binned.
    values : (N,) array_like or list of (N,) array_like
        The data on which the statistic will be computed.  This must be
        the same shape as `x`, or a set of sequences - each the same shape as
        `x`.  If `values` is a set of sequences, the statistic will be computed
        on each independently.
    statistic : string or callable, optional
        The statistic to co

In [2]:
from plottery.plotutils import savefig, update_rcParams
update_rcParams()

In [3]:
filename = 'data/eagle_L0100N1504/history/history.h5'

In [ ]:
np.random.seed(31)

In [5]:
with h5py.File(filename, 'r') as hdf:
    print(hdf.keys())
    for key in hdf.keys():
        print(key, hdf[key].keys())
    tr = hdf.get('trackids')
    print('tr', tr.items())
    trackid = np.array(hdf.get('trackids/TrackId_current_host'))
    msat = np.array(hdf.get('sat/Mbound'))
    mfinf = np.array(hdf.get('first_infall/Mbound'))
    mlinf = np.array(hdf.get('last_infall/Mbound'))
print(trackid)
msat.shape

<KeysViewHDF5 ['cent', 'first_infall', 'last_infall', 'sat', 'trackids']>
cent <KeysViewHDF5 ['Mbound', 'Mdm', 'Mgas', 'Mstar', 'isnap', 'time', 'z']>
first_infall <KeysViewHDF5 ['Mbound', 'Mdm', 'Mgas', 'Mstar', 'isnap', 'time', 'z']>
last_infall <KeysViewHDF5 ['Mbound', 'Mdm', 'Mgas', 'Mstar', 'isnap', 'time', 'z']>
sat <KeysViewHDF5 ['Mbound', 'Mdm', 'Mgas', 'Mstar', 'isnap', 'time', 'z']>
trackids <KeysViewHDF5 ['TrackId', 'TrackId_current_host', 'TrackId_previous_host']>
tr ItemsViewHDF5(<HDF5 group "/trackids" (3 members)>)
[    26  90621   1221 ... 512106 148399 512132]


(75566,)

In [7]:
print(mfinf)
print(mlinf)

[7.485e+02 1.448e+02 5.594e+01 ... 1.080e-01 2.247e-01 1.697e-01]
[7.4829114e+02 1.4473894e+02 5.3317688e+01 ... 1.0723877e-01 2.2470538e-01
 1.6963711e-01]


In [13]:
df = pd.DataFrame({'x': np.random.random(10)})

In [36]:
trackid

array([    26,  90621,   1221, ..., 512106, 148399, 512132], dtype=int32)

In [38]:
help(np.random.default_rng)

Help on built-in function default_rng in module numpy.random._generator:

default_rng(...)
    Construct a new Generator with the default BitGenerator (PCG64).
    
    Parameters
    ----------
    seed : {None, int, array_like[ints], SeedSequence, BitGenerator, Generator}, optional
        A seed to initialize the `BitGenerator`. If None, then fresh,
        unpredictable entropy will be pulled from the OS. If an ``int`` or
        ``array_like[ints]`` is passed, then it will be passed to
        `SeedSequence` to derive the initial `BitGenerator` state. One may also
        pass in a`SeedSequence` instance
        Additionally, when passed a `BitGenerator`, it will be wrapped by
        `Generator`. If passed a `Generator`, it will be returned unaltered.
    
    Returns
    -------
    Generator
        The initialized generator object.
    
    Notes
    -----
    If ``seed`` is not a `BitGenerator` or a `Generator`, a new `BitGenerator`
    is instantiated. This function does not